package com.wtu.travel.mapper;

import com.wtu.travel.bean.Img;
import com.wtu.travel.bean.ImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int countByExample(ImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int deleteByExample(ImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int insert(Img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int insertSelective(Img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    List<Img> selectByExample(ImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    Img selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int updateByExampleSelective(@Param("record") Img record, @Param("example") ImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int updateByExample(@Param("record") Img record, @Param("example") ImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int updateByPrimaryKeySelective(Img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int updateByPrimaryKey(Img record);
}