package com.wtu.travel.mapper;

import com.wtu.travel.bean.TravelDetail;
import com.wtu.travel.bean.TravelDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TravelDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_detail
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int countByExample(TravelDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_detail
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int deleteByExample(TravelDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_detail
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_detail
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int insert(TravelDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_detail
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int insertSelective(TravelDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_detail
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    List<TravelDetail> selectByExample(TravelDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_detail
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    TravelDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_detail
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int updateByExampleSelective(@Param("record") TravelDetail record, @Param("example") TravelDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_detail
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int updateByExample(@Param("record") TravelDetail record, @Param("example") TravelDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_detail
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int updateByPrimaryKeySelective(TravelDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_detail
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int updateByPrimaryKey(TravelDetail record);
}