package com.wtu.travel.mapper;

import com.wtu.travel.bean.TTravel;
import com.wtu.travel.bean.TTravelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TTravelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travel
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int countByExample(TTravelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travel
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int deleteByExample(TTravelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travel
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travel
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int insert(TTravel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travel
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int insertSelective(TTravel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travel
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    List<TTravel> selectByExample(TTravelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travel
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    TTravel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travel
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int updateByExampleSelective(@Param("record") TTravel record, @Param("example") TTravelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travel
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int updateByExample(@Param("record") TTravel record, @Param("example") TTravelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travel
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int updateByPrimaryKeySelective(TTravel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travel
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    int updateByPrimaryKey(TTravel record);
}