package com.wtu.travel.bean;

public class Img {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.id
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.adress
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    private String adress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.parent
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    private Integer parent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.id
     *
     * @return the value of img.id
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.id
     *
     * @param id the value for img.id
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.adress
     *
     * @return the value of img.adress
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.adress
     *
     * @param adress the value for img.adress
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public void setAdress(String adress) {
        this.adress = adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.parent
     *
     * @return the value of img.parent
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.parent
     *
     * @param parent the value for img.parent
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }
}