package com.wtu.travel.bean;

public class TravelDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_detail.id
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_detail.context
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    private String context;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_detail.parent
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    private Integer parent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_detail.id
     *
     * @return the value of travel_detail.id
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_detail.id
     *
     * @param id the value for travel_detail.id
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_detail.context
     *
     * @return the value of travel_detail.context
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_detail.context
     *
     * @param context the value for travel_detail.context
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public void setContext(String context) {
        this.context = context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_detail.parent
     *
     * @return the value of travel_detail.parent
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_detail.parent
     *
     * @param parent the value for travel_detail.parent
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }
}