package com.wtu.travel.bean;

import java.util.Date;

public class TTravel {
    private User realAuthour;

    public User getRealAuthour() {
        return realAuthour;
    }

    public void setRealAuthour(User realAuthour) {
        this.realAuthour = realAuthour;
    }
    private TravelDetail travelDetail;

    public TravelDetail getTravelDetail() {
        return travelDetail;
    }

    public void setTravelDetail(TravelDetail travelDetail) {
        this.travelDetail = travelDetail;
    }

    private Img img;

    public Img getImg() {
        return img;
    }

    public void setImg(Img img) {
        this.img = img;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_travel.id
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_travel.title
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_travel.region
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_travel.authour
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    private Integer authour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_travel.date
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_travel.id
     *
     * @return the value of t_travel.id
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_travel.id
     *
     * @param id the value for t_travel.id
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_travel.title
     *
     * @return the value of t_travel.title
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_travel.title
     *
     * @param title the value for t_travel.title
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_travel.region
     *
     * @return the value of t_travel.region
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_travel.region
     *
     * @param region the value for t_travel.region
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_travel.authour
     *
     * @return the value of t_travel.authour
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public Integer getAuthour() {
        return authour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_travel.authour
     *
     * @param authour the value for t_travel.authour
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public void setAuthour(Integer authour) {
        this.authour = authour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_travel.date
     *
     * @return the value of t_travel.date
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_travel.date
     *
     * @param date the value for t_travel.date
     *
     * @mbggenerated Sun May 22 15:23:59 CST 2022
     */
    public void setDate(Date date) {
        this.date = date;
    }
}